[-] Remove aa script [~] Add action.yml to mkproject script [~] Change check_coding_style job in action.yml [+] Remove Notify Discord step in check_program_compilation & run_tests

diff --git a/Template/.github/workflows/action.yml b/Template/.github/workflows/action.yml
--- a/Template/.github/workflows/action.yml
+++ b/Template/.github/workflows/action.yml
@@ -3,9 +3,6 @@ name: project_name
 env:
   EXECUTABLE:
     binary_name
-  WEBHOOK_URL:
-    ${{ secrets.DISCORD_WEBHOOK_URL_SECRET }}
-
 
 on:
   [push, pull_request]
@@ -19,14 +16,24 @@ jobs:
         uses: actions/checkout@v4.1.1
       - name: Check coding-style
         run: |
-          docker run --rm --security-opt "label:disable" -i -v "$(pwd)":"/mnt/delivery" -v "$(pwd)":"/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports" ;
+          docker run --rm --security-opt "label:disable" -i -v "$(pwd)":"/mnt/delivery" -v "$(pwd)":"/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports"
       - name: Display coding-style report
         run: |
-          chmod +x .github/workflows/display_codingstyle.sh
-          .github/workflows/display_codingstyle.sh
-      - name: Notify Discord
+          input="coding-style-reports.log"
+          if [ ! -f "$input" ]; then
+              echo "Error: Input file '$input' not found."
+              curl -X POST -H "Content-Type: application/json" -d '{"content": "Error: Input file '$input' not found."}' $WEBHOOK_URL
+              exit 1
+          fi
+          while IFS=": " read -r file line title description; do
+              echo "::error title=$title coding style error,file=$file,line=$line::$description"
+          done < "$input"
+      - name: Report banana result
         run: |
-          curl -X POST -H "Content-Type: application/json" -d '{"content": "Check coding-style job completed."}' $WEBHOOK_URL
+          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            exit 1
+          fi
 
   check_program_compilation:
       name: Check program compilation
@@ -48,9 +55,6 @@ jobs:
                 exit 1
               fi
             done
-        - name: Notify Discord
-          run: |
-            curl -X POST -H "Content-Type: application/json" -d '{"content": "Check program compilation job completed."}' $WEBHOOK_URL
 
   run_tests:
     name: Run tests
@@ -63,6 +67,3 @@ jobs:
         uses: actions/checkout@v4.1.1
       - name: Run tests
         run: make tests_run
-      - name: Notify Discord
-        run: |
-          curl -X POST -H "Content-Type: application/json" -d '{"content": "Run tests job completed."}' $WEBHOOK_URL
diff --git a/mkproject b/mkproject
--- a/mkproject
+++ b/mkproject
@@ -3,25 +3,25 @@
 # Check if there are enough arguments
 if [ $# -lt 2 ]; then
     echo "Error: You must provide exactly two arguments."
-    echo "Usage: <folder_name> <binary_name>"
+    echo "Usage: <project_name> <binary_name>"
     exit 1
 fi
 
 # Retrieve the folder name to be created from the first parameter
-folder_name=$1
+project_name=$1
 binary_name=$2
 
 # Check if the folder already exists
-if [ -d "$folder_name" ]; then
-    echo "Error: The folder $folder_name already exists. Choose another name."
+if [ -d "$project_name" ]; then
+    echo "Error: The folder $project_name already exists. Choose another name."
     exit 1
 fi
 
 # Create the new folder
-mkdir "$folder_name"
+mkdir "$project_name"
 
 # Reference folder containing the folders to copy
-reference_folder="/home/christophe/Epitech/Template"
+reference_folder="/home/christophe/my_scripts/Template"
 
 # Check if the reference folder exists
 if [ ! -d "$reference_folder" ]; then
@@ -30,21 +30,28 @@ if [ ! -d "$reference_folder" ]; then
 fi
 
 # Copy folders from the reference folder to the new folder
-cp -r "$reference_folder"/* "$folder_name"
-cp "$reference_folder/.gitignore" "$folder_name/"
+cp -r "$reference_folder"/* "$project_name"
+cp "$reference_folder/.gitignore" "$project_name/"
+cp -r "$reference_folder/.github" "$project_name/"
 
-cd "$folder_name" || exit
+cd "$project_name" || exit
 
-sed -i "s|\bproject_name\b|$folder_name|" "Makefile"
+sed -i "s|\bproject_name\b|$project_name|" "Makefile"
 sed -i "s|\bbinary_name\b|$binary_name|" "Makefile"
 sed -i "s|\bbinary_name\b|$binary_name|" ".gitignore"
 
 cd "src" || exit
 
-sed -i "s|\bproject_name\b|$folder_name|" "main.c"
+sed -i "s|\bproject_name\b|$project_name|" "main.c"
 
-echo "The folder $folder_name has been successfully created, and the folders have been copied."
+cd ".." || exit
+
+cd ".github/workflows" || exit
+
+sed -i "s|\bproject_name\b|$project_name|" "action.yml"
+sed -i "s|\bbinary_name\b|$binary_name|" "action.yml"
+
+echo "The folder $project_name has been successfully created, and the folders have been copied."
 echo "The binary name $binary_name in the Makefile has been applied"
 
 exit 0
-
